#!/usr/bin/env python3
"""
_gen_master_script.py
=====================
Generator for ``setup_pioneer_nav.sh``. Reads every file under pioneer_nav_ws/
(except build artefacts, .git, the script itself, and the generated output)
and emits a single self-contained bash script that recreates the whole
workspace via heredocs, then builds, sources, and launches it.

Usage::

    python3 tools/_gen_master_script.py             # writes ../setup_pioneer_nav.sh
    python3 tools/_gen_master_script.py -o /tmp/x   # custom output path

The output script is intentionally human-readable so the user can audit
what each section writes before running it.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import List


SKIP_DIRS = {'.git', 'build', 'install', 'log', '__pycache__', '.pytest_cache'}
SKIP_FILES = {'_gen_master_script.py', 'setup_pioneer_nav.sh'}


def collect_files(root: Path) -> List[Path]:
    out: List[Path] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for f in sorted(filenames):
            if f in SKIP_FILES:
                continue
            out.append(Path(dirpath) / f)
    return sorted(out)


HEADER = r'''#!/usr/bin/env bash
# =============================================================================
# setup_pioneer_nav.sh
# Auto-generated master setup script for the pioneer_nav_ws (scoutbot AGV)
# ROS2 Humble waypoint-navigation project.
#
# This single script:
#   1. Verifies host environment (Ubuntu 22.04 + ROS 2 Humble + colcon).
#   2. Installs missing apt dependencies (idempotent).
#   3. Creates the workspace and writes every source/config/launch file.
#   4. Builds the workspace with colcon.
#   5. Sources install/setup.bash.
#   6. Runs offline static checks (tools/check_workspace.sh).
#   7. Optionally launches scout_full_stack and runs runtime diagnostics.
#
# USAGE
#   bash setup_pioneer_nav.sh                # build + static check, no launch
#   bash setup_pioneer_nav.sh --launch       # build + launch full stack
#   bash setup_pioneer_nav.sh --no-build     # write files only
#   bash setup_pioneer_nav.sh --force        # overwrite existing files
#   bash setup_pioneer_nav.sh --dry-run      # list every file it would write
#
# REGENERATION
#   This script was generated by tools/_gen_master_script.py.
#   To regenerate after editing any file under src/, run:
#       python3 tools/_gen_master_script.py
# =============================================================================
set -uo pipefail

# ---- options ----------------------------------------------------------------
WS_NAME="pioneer_nav_ws"
WS_DIR="${WS_DIR:-${HOME}/${WS_NAME}}"
DO_BUILD=1
DO_LAUNCH=0
FORCE=0
DRY_RUN=0
for arg in "$@"; do
  case "${arg}" in
    --launch)   DO_LAUNCH=1 ;;
    --no-build) DO_BUILD=0  ;;
    --force)    FORCE=1     ;;
    --dry-run)  DRY_RUN=1   ;;
    -h|--help)
      sed -n '2,30p' "$0"; exit 0;;
    *) echo "Unknown option: ${arg}" >&2; exit 1;;
  esac
done

GREEN='\033[0;32m'; RED='\033[0;31m'; YEL='\033[0;33m'; NC='\033[0m'
say()  { echo -e "${GREEN}==>${NC} $*"; }
warn() { echo -e "${YEL}==>${NC} $*"; }
fail() { echo -e "${RED}!!${NC}  $*" >&2; exit 1; }

# ---- environment checks -----------------------------------------------------
check_env() {
  say "Checking host environment"
  if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    if [[ "${ID:-}" != "ubuntu" || "${VERSION_ID:-}" != "22.04" ]]; then
      warn "Detected ${ID:-?} ${VERSION_ID:-?}; ROS2 Humble targets Ubuntu 22.04 (jammy). Continuing anyway."
    else
      echo "  OK Ubuntu 22.04"
    fi
  fi
  if [[ -z "${ROS_DISTRO:-}" ]]; then
    warn "ROS_DISTRO not set in this shell. Trying /opt/ros/humble/setup.bash"
    if [[ -f /opt/ros/humble/setup.bash ]]; then
      # shellcheck disable=SC1091
      source /opt/ros/humble/setup.bash
    else
      fail "ROS 2 Humble not found. Install ros-humble-desktop first."
    fi
  fi
  echo "  OK ROS_DISTRO=${ROS_DISTRO}"
  command -v colcon >/dev/null 2>&1 || fail "colcon not found (sudo apt install python3-colcon-common-extensions)"
  command -v xacro  >/dev/null 2>&1 || fail "xacro not found (sudo apt install ros-humble-xacro)"
  echo "  OK colcon + xacro"
}

# ---- apt dependencies (idempotent) ------------------------------------------
install_deps() {
  say "Installing apt dependencies (sudo required, idempotent)"
  local pkgs=(
    ros-humble-xacro
    ros-humble-robot-state-publisher
    ros-humble-joint-state-publisher
    ros-humble-joint-state-publisher-gui
    ros-humble-rviz2
    ros-humble-gazebo-ros-pkgs
    ros-humble-gazebo-ros2-control
    ros-humble-ros2-control
    ros-humble-ros2-controllers
    ros-humble-controller-manager
    ros-humble-diff-drive-controller
    ros-humble-joint-state-broadcaster
    ros-humble-tf-transformations
    ros-humble-teleop-twist-keyboard
    python3-colcon-common-extensions
    python3-yaml
    python3-pytest
  )
  if sudo -n true 2>/dev/null; then
    sudo apt-get update -y
    sudo apt-get install -y --no-install-recommends "${pkgs[@]}"
  else
    warn "sudo not available without password; skipping apt install. Ensure these are present:"
    printf '  - %s\n' "${pkgs[@]}"
  fi
}

# ---- write_file: heredoc helper ---------------------------------------------
# Usage: write_file <relative-path>  (content read from stdin until WRITE_EOF)
write_file() {
  local rel="$1"
  local abs="${WS_DIR}/${rel}"
  if (( DRY_RUN )); then
    printf '  WOULD WRITE %s\n' "${rel}"
    cat >/dev/null
    return 0
  fi
  if [[ -e "${abs}" && ${FORCE} -eq 0 ]]; then
    printf '  SKIP   %s (exists; use --force to overwrite)\n' "${rel}"
    cat >/dev/null
    return 0
  fi
  mkdir -p "$(dirname "${abs}")"
  cat > "${abs}"
  printf '  WRITE  %s\n' "${rel}"
}

write_all_files() {
  say "Writing files into ${WS_DIR}"
  mkdir -p "${WS_DIR}"

'''


FOOTER = r'''
}

# ---- build, source, verify, launch -----------------------------------------
build_ws() {
  say "Building workspace (colcon build --symlink-install)"
  pushd "${WS_DIR}" >/dev/null
  colcon build --symlink-install --event-handlers console_cohesion+ \
      || fail "colcon build failed"
  popd >/dev/null
}

source_ws() {
  say "Sourcing workspace"
  # shellcheck disable=SC1091
  source "${WS_DIR}/install/setup.bash"
  echo "  OK packages now visible:"
  ros2 pkg list 2>/dev/null | grep '^scoutbot_' | sed 's/^/    /'
}

static_check() {
  say "Running offline static checks"
  bash "${WS_DIR}/tools/check_workspace.sh" || fail "static check failed"
}

launch_full_stack() {
  say "Launching scout_full_stack.launch.py (Ctrl-C to stop)"
  warn "Open a SECOND terminal and run:"
  echo  "    source ${WS_DIR}/install/setup.bash"
  echo  "    bash   ${WS_DIR}/tools/diagnose_runtime.sh"
  ros2 launch scoutbot_bringup scout_full_stack.launch.py
}

# ---- main flow --------------------------------------------------------------
check_env
if (( ! DRY_RUN )); then install_deps; fi
write_all_files
if (( DRY_RUN )); then
  say "DRY RUN complete. No files written."
  exit 0
fi

if (( DO_BUILD )); then
  build_ws
  source_ws
  static_check
  if (( DO_LAUNCH )); then
    launch_full_stack
  else
    say "Build + static check OK. Launch with:  bash $0 --launch"
  fi
else
  say "Files written (build skipped). Run colcon build manually:"
  echo "    cd ${WS_DIR} && colcon build --symlink-install"
fi
'''


def emit_block(rel: str, contents: bytes, eof_tag: str = 'WRITE_EOF') -> str:
    """Emit a 'write_file <rel> <<...EOF\n...\nEOF' block.

    We choose a heredoc tag that is guaranteed not to appear in the file's
    contents. Single-quoted heredoc tag means NO shell expansion -- so $foo
    inside .py / .yaml / .xacro stays literal.
    """
    text = contents.decode('utf-8', errors='replace')
    tag = eof_tag
    while ('\n' + tag + '\n') in ('\n' + text + '\n'):
        tag += '_X'
    return f"  write_file {shlex_q(rel)} <<'{tag}'\n{text}{'' if text.endswith(chr(10)) else chr(10)}{tag}\n"


def shlex_q(s: str) -> str:
    """Minimal shell-quote that always works for our paths (no spaces)."""
    if all(c.isalnum() or c in '._-/' for c in s):
        return s
    return "'" + s.replace("'", "'\\''") + "'"


def main(argv: List[str] | None = None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument('-o', '--output', default=None,
                   help='Output script path (default: ../setup_pioneer_nav.sh)')
    args = p.parse_args(argv)

    here = Path(__file__).resolve().parent
    ws_root = here.parent
    out = Path(args.output) if args.output else (ws_root.parent / 'setup_pioneer_nav.sh')

    files = collect_files(ws_root)
    if not files:
        print('ERROR: no files found under', ws_root, file=sys.stderr)
        return 1

    parts = [HEADER]
    for f in files:
        rel = f.relative_to(ws_root.parent).as_posix()  # e.g. pioneer_nav_ws/src/...
        # Trim off leading "pioneer_nav_ws/" so write_file places relative to WS_DIR
        if rel.startswith('pioneer_nav_ws/'):
            rel_in_ws = rel[len('pioneer_nav_ws/'):]
        else:
            rel_in_ws = rel
        parts.append(emit_block(rel_in_ws, f.read_bytes()))
    parts.append(FOOTER)

    out.write_text(''.join(parts))
    out.chmod(0o755)
    print(f'Wrote {out} ({out.stat().st_size:,} bytes, {len(files)} files)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
